### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [iColtz/hypixel-api#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by iColtz** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

If your wanting to do that sure go ahead submit a pull request. 👍

**Comment by geopic** [comment]
Great, I'll start on it now.
